name: Manual Integration Tests

on:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        id: build
        run: dotnet build --no-restore --configuration Release

      - name: Run integration tests
        run: dotnet test tests/Yaref92.Events.IntegrationTests --configuration Release --logger "trx;LogFileName=test_results.trx" --filter TestCategory=Integration

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{steps.build.outcome == 'success'}}
        with:
          files: tests/Yaref92.Events.IntegrationTests/TestResults/*.trx
          check_name: "Integration tests Results"
